// import React from 'react'
// import { Route, Routes } from 'react-router-dom'
// import {Home} from './src/Components/Home/Home'
// import{ About} from './src/Components/About/About'
// import {Contact} from './src/contact'
// import { Skills } from './src/Components/Skills/Skills'
// import {Project} from './src/project'
// import {Layout} from './components/layout'
// import { Navbar } from './src/Components/Navbar/Navbar'
// import { TabBar } from './src/Components/TabBar/TabBar'